name: m3u8_download
on:
  workflow_dispatch:
    inputs:
      M3U8_URL:
        description: 'M3U8_URL'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Download Tool
        run: |
          curl https://hub.njuu.cf/nilaoda/N_m3u8DL-CLI/releases/download/3.0.2/N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG.zip
          unzip N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG.zip
          cd N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG
          ./N_m3u8DL-CLI_v3.0.2.exe ${{ github.event.inputs.M3U8_URL }}
      - name: Upload Video
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "${{ github.workspace }}/Tool-SGSI-build/upload_ab/*,${{ github.workspace }}/Tool-SGSI-build/upload_aonly/*"
          tag: "${{ github.event.inputs.REPACK_NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "${{ github.workspace }}/Tool-SGSI-build/SGSI/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
